Understrap site info customizer setting
understrap/understrap pull request #1389
Opened 2021-08-24 01:22 UTC by gabrielcastillo

Add customizer option for understrap_site_info output.

## Description
New site info override option located in the customizer -> theme layout settings.
This feature allows users to override the default site info provided by the "understrap_site_info()" function.

## Motivation and Context
This is just a featured that allow's users/admin to change the text/info provided by the understrap_site_info function.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] I have checked that there aren't other open Pull Requests for the same update/change.
- [x] My code follows the code style of this project.
- [x] I have performed a self-review of my own code.
- [x] I have commented my code, particularly in hard-to-understand areas.
- [x] \(Optional) My change requires a change to the documentation.
- [ ] \(Optional) I have updated the documentation accordingly.
- [ ] \(Optional) My change requires a change to the translations.
- [ ] \(Optional) I have updated the translations accordingly.
- [ ] `composer cs:check` has passed locally.
- [ ] `composer lint:php` has passed locally.
- [x] I have read the **CONTRIBUTING** document.

## Further comments

2021-08-24 22:06 UTC, bacoords requested changes

2021-08-25 00:54 UTC, gabrielcastillo commented on inc/customizer.php
> +                    'label' => __('Understrap Site Info Override - Footer', 'understrap'),
Done.

2021-08-25 00:54 UTC, gabrielcastillo commented on inc/hooks.php
> +            echo get_theme_mod('understrap_site_info_override');
updated to your suggestion.

2021-08-25 13:54 UTC, bacoords submitted a review, later dismissed

2021-08-25 13:56 UTC, bacoords approved these changes

2021-08-25 13:56 UTC, merged